<a href="https://colab.research.google.com/github/Rohini2407/Rohi/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
from google.colab import files

In [22]:
upload = files.upload()

Saving MallCustomers.csv to MallCustomers (1).csv

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv("MallCustomers.csv")

In [25]:
df.head(10)

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40
5           6  Female   22                  17                      76
6           7  Female   35                  18                       6
7           8  Female   23                  18                      94
8           9    Male   64                  19                       3
9          10  Female   30                  19                      72

In [26]:
df.columns

Index(['CustomerID', 'Genre', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [27]:
type(df)

pandas.core.frame.DataFrame

In [28]:
df['Genre']

0        Male
1        Male
2      Female
3      Female
4      Female
        ...
195    Female
196    Female
197      Male
198      Male
199      Male
Name: Genre, Length: 200, dtype: object

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Genre                   200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [30]:
df.isna().sum()

CustomerID                0
Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [31]:
type(df['Age'])

pandas.core.series.Series

In [32]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [33]:
df['Genre'].value_counts()

Female    112
Male       88
Name: Genre, dtype: int64

In [34]:
df.iloc[0,2]

19

In [35]:
df.iloc[0]

CustomerID                   1
Genre                     Male
Age                         19
Annual Income (k$)          15
Spending Score (1-100)      39
Name: 0, dtype: object

In [36]:
df.iloc[0:11,0:2]

    CustomerID   Genre
0            1    Male
1            2    Male
2            3  Female
3            4  Female
4            5  Female
5            6  Female
6            7  Female
7            8  Female
8            9    Male
9           10  Female
10          11    Male

In [37]:
df.loc[0:5,'Genre':'Annual Income (k$)']  #df.loc[rows,columns]

    Genre  Age  Annual Income (k$)
0    Male   19                  15
1    Male   21                  15
2  Female   20                  16
3  Female   23                  16
4  Female   31                  17
5  Female   22                  17

In [38]:
people={
    "first":["aryan","uday","divij"],
    "last":["sonawane","talele","kulkarni"],
    "email":["aryans.nsk@gmail.com","ut@gmail.com","macenth@gmail.com"]
}

In [39]:
df = pd.DataFrame(people)

In [40]:
df

   first      last                 email
0  aryan  sonawane  aryans.nsk@gmail.com
1   uday    talele          ut@gmail.com
2  divij  kulkarni     macenth@gmail.com

In [40]:
df.set_Index('email',inplace = True)  #used to set an index,return in bold

In [41]:
df.drop('email',axis = 1,inplace = True)

In [42]:
df.drop(2,axis = 0,inplace = True)

In [43]:
df2={'email':['ratspawar@gmail.com','dips@gmail.com','tans@gmail.com'],
     'first':['ratnali','deepali','tanmayi'],
     'last':['pawar','khajure','shete']}

In [44]:
df = df.append(df2,ignore_Index = True)

TypeError: ignored

In [ ]:
df

In [ ]:
filt = df['Genre'] == 'Female'

In [45]:
df

   first      last
0  aryan  sonawane
1   uday    talele

In [47]:
filt=df['Genre']=='Female'

KeyError: ignored

In [48]:
df = pd.read_csv("MallCustomers.csv")

In [49]:
filt=df['Genre']=='Female'

In [50]:
df[filt]

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
..          ...     ...  ...                 ...                     ...
191         192  Female   32                 103                      69
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28

[112 rows x 5 columns]

In [51]:
filt1 = (df['Genre']=='Female')&(df['Spending Score (1-100)']>=75)

In [52]:
df[filt1]

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
3             4  Female   23                  16                      77
5             6  Female   22                  17                      76
7             8  Female   23                  18                      94
11           12  Female   35                  19                      99
13           14  Female   24                  20                      77
19           20  Female   35                  23                      98
29           30  Female   23                  29                      87
35           36  Female   21                  33                      81
39           40  Female   20                  37                      75
125         126  Female   31                  70                      77
135         136  Female   29                  73                      88
143         144  Female   32                  76                      87
153         154  Female   38                  78                      76
155         156  Female   27                  78                      89
157         158  Female   30                  78                      78
161         162  Female   29                  79                      83
163         164  Female   31                  81                      93
165         166  Female   36                  85                      75
167         168  Female   33                  86                      95
175         176  Female   30                  88                      86
181         182  Female   32                  97                      86
183         184  Female   29                  98                      88
189         190  Female   36                 103                      85
193         194  Female   38                 113                      91
195         196  Female   35                 120                      79